# lexer_tab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('AND_OP', 'AS_CLAUSE', 'BOTTOM_OP', 'BY_CLAUSE', 'CASE_OP', 'CMD_ABSTRACT', 'CMD_ACCUM', 'CMD_ADDCOLTOTALS', 'CMD_ADDINFO', 'CMD_ADDTOTALS', 'CMD_ANALYSEFIELDS', 'CMD_ANOMALIES', 'CMD_ANOMALOUSVALUE', 'CMD_ANOMALYDETECTION', 'CMD_APPEND', 'CMD_APPENDCOLS', 'CMD_APPENDPIPE', 'CMD_ARULES', 'CMD_ASSOCIATE', 'CMD_AUDIT', 'CMD_AUTOREGRESS', 'CMD_BIN', 'CMD_BUCKETDIR', 'CMD_CEFOUT', 'CMD_CHART', 'CMD_CLUSTER', 'CMD_COFILTER', 'CMD_COLLECT', 'CMD_CONCURRENCY', 'CMD_CONTINGENCY', 'CMD_CONVERT', 'CMD_CORRELATE', 'CMD_DATAMODEL', 'CMD_DBINSPECT', 'CMD_DEDUP', 'CMD_DELETE', 'CMD_DELTA', 'CMD_DIFF', 'CMD_EREX', 'CMD_EVAL', 'CMD_EVENTCOUNT', 'CMD_EVENTSTATS', 'CMD_EXPAND', 'CMD_EXTRACT', 'CMD_FIELDFORMAT', 'CMD_FIELDS', 'CMD_FIELDSUMMARY', 'CMD_FILLDOWN', 'CMD_FILLNULL', 'CMD_FINDTYPES', 'CMD_FLATTEN', 'CMD_FOLDERIZE', 'CMD_FOREACH', 'CMD_FORMAT', 'CMD_FROM', 'CMD_GAUGE', 'CMD_GENTIMES', 'CMD_GEOM', 'CMD_GEOMFILTER', 'CMD_GEOSTATS', 'CMD_HEAD', 'CMD_HIGHLIGHT', 'CMD_HISTORY', 'CMD_ICONIFY', 'CMD_INPUTCSV', 'CMD_INPUTLOOKUP', 'CMD_IPLOCATION', 'CMD_JOIN', 'CMD_KMEANS', 'CMD_KVFORM', 'CMD_LOADJOB', 'CMD_LOCALIZE', 'CMD_LOCALOP', 'CMD_LOOKUP', 'CMD_MAKECONTINUOUS', 'CMD_MAKEMV', 'CMD_MAKERESULTS', 'CMD_MAP', 'CMD_MCOLLECT', 'CMD_METADATA', 'CMD_METASEARCH', 'CMD_MEVENTCOLLECT', 'CMD_MPREVIEW', 'CMD_MSTATS', 'CMD_MULTIKV', 'CMD_MULTISEARCH', 'CMD_MVCOMBINE', 'CMD_MVEXPAND', 'CMD_NOMV', 'CMD_OUTLIER', 'CMD_OUTPUTCSV', 'CMD_OUTPUTLOOKUP', 'CMD_OUTPUTTEXT', 'CMD_PIVOT', 'CMD_PREDICT', 'CMD_RANGEMAP', 'CMD_RARE', 'CMD_REDISTRIBUTE', 'CMD_REGEX', 'CMD_RELEVANCY', 'CMD_RELTIME', 'CMD_RENAME', 'CMD_REPLACE', 'CMD_REQUIRE', 'CMD_REST', 'CMD_RETURN', 'CMD_REVERSE', 'CMD_REX', 'CMD_RTORDER', 'CMD_SAVEDSEARCH', 'CMD_SCRIPT', 'CMD_SCRUB', 'CMD_SEARCH', 'CMD_SEARCHTXN', 'CMD_SELFJOIN', 'CMD_SENDEMAIL', 'CMD_SET', 'CMD_SETFIELDS', 'CMD_SICHART', 'CMD_SISTATS', 'CMD_SITIMECHART', 'CMD_SITOP', 'CMD_SORT', 'CMD_SPATH', 'CMD_STATS', 'CMD_STRCAT', 'CMD_STREAMSTATS', 'CMD_TABLE', 'CMD_TAGS', 'CMD_TAIL', 'CMD_TIMECHART', 'CMD_TIMEWRAP', 'CMD_TOP', 'CMD_TRANSACTION', 'CMD_TRANSPOSE', 'CMD_TRENDLINE', 'CMD_TSCOLLECT', 'CMD_TSTATS', 'CMD_TYPEAHEAD', 'CMD_TYPELEARNER', 'CMD_TYPER', 'CMD_UNION', 'CMD_UNIQ', 'CMD_UNTABLE', 'CMD_WALKLEX', 'CMD_WHERE', 'CMD_X11', 'CMD_XMLKV', 'CMD_XMLUNESCAPE', 'CMD_XPATH', 'CMD_XYSERIES', 'COLON', 'COLSUMMARY_OP', 'COMMA', 'COMP_OP', 'DATE', 'DEQ', 'DIVIDE', 'DOT', 'EQ', 'FALSELABEL_OP', 'FILTER_OP', 'FLOAT', 'GROUPBY_CLAUSE', 'IN_OP', 'LBRACK', 'LIMIT_OP', 'LPAREN', 'MACRO', 'MINUS', 'MOD', 'NAME', 'NEQ', 'NOTCHAR', 'NOTIN_OP', 'NOT_OP', 'NUMBER', 'NUMCOLS_OP', 'OR_OP', 'OUTPUT_NEW_OP', 'OUTPUT_OP', 'OVER_OP', 'PATTERN', 'PERIOD_OP', 'PIPE', 'PLUS', 'PREFIX_OP', 'QLPAREN', 'QRPAREN', 'QUOTE', 'RANGE_OP', 'RBRACK', 'ROWSUMMARY_OP', 'RPAREN', 'SHOWOTHER_OP', 'SORTBY_CLAUSE', 'SPLITCOL_OP', 'SPLITROW_OP', 'STRING', 'TERM_OP', 'TEXT', 'TIMES', 'TIMESPECIFIER', 'TRUELABEL_OP', 'WITH_OP'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_MACRO>`([a-zA-Z][a-zA-Z0-9_\\.-]*)(\\(([^,\\(\\)]+(,[^,\\(\\)]+)*)\\))?`)|(?P<t_newline>\\n+)|(?P<t_DATE>\\d+/\\d+/\\d+(:\\d+:\\d+:\\d+)?)|(?P<t_PATTERN>(\\*[a-zA-Z_\\.\\{\\}\\-:<>/\\\\\\*]+|[a-zA-Z0-9_\\.\\{\\}\\-:<>/\\\\\\*]+\\*))|(?P<t_STRING>("([^"\\\\]*(\\\\.[^"\\\\]*)*)"|\\\'([^\\\'\\\\]*(\\\\.[^\\\'\\\\]*)*)\\\'|""|\\\'\\\'))|(?P<t_NAME>([a-zA-Z0-9_\\{\\}/\\\\]*<<[a-zA-Z0-9_\\{\\}/@\\\\]+>>[a-zA-Z0-9_\\{\\}/\\\\]*|[a-zA-Z0-9_\\{\\}\\$\\\\][a-zA-Z0-9_\\{\\}\\-:/@\\\\\\.]*[a-zA-Z0-9_\\{\\}\\$\\\\]|[a-zA-Z0-9_\\{\\}\\$\\\\][a-zA-Z0-9_\\{\\}\\-:/@\\\\]*))|(?P<t_TIMESPECIFIER>[0-9a-zA-Z\\+\\-]*@[0-9a-zA-Z\\+\\-]+ )|(?P<t_FLOAT>\\d*\\.\\d+)|(?P<t_NUMBER>\\d+)|(?P<t_TEXT>[^\\| =><\\[\\]"\\\'\\(\\)\\+\\*-/!\\,]+)|(?P<t_COMP_OP>(<=|>=|<|>))|(?P<t_QLPAREN>\\"\\(\\")|(?P<t_QRPAREN>\\"\\)\\")|(?P<t_DEQ>\\=\\=)|(?P<t_NEQ>!\\=)|(?P<t_EQ>\\=)|(?P<t_PLUS>\\+)|(?P<t_TIMES>\\*)|(?P<t_LPAREN>\\()|(?P<t_RPAREN>\\))|(?P<t_LBRACK>\\[)|(?P<t_RBRACK>\\])|(?P<t_PIPE>\\|)|(?P<t_COMMA>\\,)|(?P<t_DOT>\\.)|(?P<t_NOTCHAR>!)|(?P<t_MINUS>-)|(?P<t_DIVIDE>/)|(?P<t_MOD>%)|(?P<t_QUOTE>")|(?P<t_COLON>:)', [None, ('t_MACRO', 'MACRO'), None, None, None, None, ('t_newline', 'newline'), ('t_DATE', 'DATE'), None, ('t_PATTERN', 'PATTERN'), None, ('t_STRING', 'STRING'), None, None, None, None, None, ('t_NAME', 'NAME'), None, ('t_TIMESPECIFIER', 'TIMESPECIFIER'), ('t_FLOAT', 'FLOAT'), ('t_NUMBER', 'NUMBER'), ('t_TEXT', 'TEXT'), (None, 'COMP_OP'), None, (None, 'QLPAREN'), (None, 'QRPAREN'), (None, 'DEQ'), (None, 'NEQ'), (None, 'EQ'), (None, 'PLUS'), (None, 'TIMES'), (None, 'LPAREN'), (None, 'RPAREN'), (None, 'LBRACK'), (None, 'RBRACK'), (None, 'PIPE'), (None, 'COMMA'), (None, 'DOT'), (None, 'NOTCHAR'), (None, 'MINUS'), (None, 'DIVIDE'), (None, 'MOD'), (None, 'QUOTE'), (None, 'COLON')])]}
_lexstateignore = {'INITIAL': ' \r\n\t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
